server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

app:
  auth:
    tokenSecret: ${app.auth.token.secret}
    tokenExpirationDay: 30
  firebase-bucket: ${app.auth.firebase-bucket}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
