spring:
  datasource:
    url: "jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: ${rds.driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true

app:
  auth:
    tokenSecret: ${app.auth.token.secret}
    tokenExpirationDay: 30
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
